#!/usr/bin/env bash
set -e

export CS_HOME=$TRAVIS_BUILD_DIR

if [ $CORESHOP_RUN_ECS == 0 ]; then
    $CS_HOME/etc/travis/setup/tests/before_install
else
    $CS_HOME/etc/travis/setup/ecs/before_install
fi