#!/usr/bin/env bash
set -e

export CS_HOME=$TRAVIS_BUILD_DIR

if [ $CORESHOP_RUN_ECS == 0 ]; then
    $TRAVIS_BUILD_DIR/etc/travis/setup/tests/install
else
    $TRAVIS_BUILD_DIR/etc/travis/setup/ecs/install
fi