#!/usr/bin/env bash
set -e

vendor/bin/phpunit -c lib/CoreShop/tests/config/ --bootstrap vendor/coreshop/core-shop/tests/phpunit-bootstrap.php lib/CoreShop/tests/lib/CoreShop/Test/PHPUnit/Suites/AllTests