services:
  _defaults:
    public: true

  CoreShop\Bundle\MoneyBundle\AdminClass\EventListener\IndexActionSettingsSubscriber:
    arguments:
      - '%coreshop.currency.decimal_precision%'
      - '%coreshop.currency.decimal_factor%'
    tags:
      - { name: kernel.event_subscriber }
