#!/usr/bin/env bash
set -e

# add config templates
mkdir -p $CS_HOME/var/config
cp $CS_HOME/lib/CoreShop/etc/_config/system.template.php var/config/system.php
cp app/config/parameters.example.yml app/config/parameters.yml

# Remove vrana/jush as its only causing problems
composer remove vrana/jush --no-scripts
composer install --no-dev --no-scripts
composer remove codeception/codeception --dev --no-scripts

# Add path to CoreShop
composer config repositories.coreshop path $CS_HOME/lib/CoreShop

cat composer.json

composer require doctrine/instantiator:1.0.5 symfony/phpunit-bridge:^3 phpunit/phpunit:^6 coreshop/core-shop:dev-$CS_BRANCH#$CS_COMMIT


if [ $CORESHOP_RUN_BEHAT == 1 ]; then
    composer require behat/behat:^3.3 friends-of-behat/context-service-extension:^1.1 friends-of-behat/cross-container-extension:^1.1 friends-of-behat/service-container-extension:^1.0 friends-of-behat/symfony-extension:^1.2 friends-of-behat/variadic-extension:^1.1 --no-scripts
fi

rm -rf var/cache

cp $CS_HOME/lib/CoreShop/etc/config/config.yml app/config/config.yml