#!/usr/bin/env bash
set -e

echo "Validating CoreShop Suite"
composer validate --strict

if [[ "$PIMCORE_VERSION" != "dev-master" ]];
then
    composer validate --strict
fi

packages="$(find "$(pwd)/src/CoreShop" -mindepth 3 -maxdepth 3 -type f -name composer.json -exec dirname '{}' \;)"

for package in $packages
do
    echo "Validating Package" "$(basename "$package")"
    composer validate --ansi --strict $package/composer.json
done
