INSERT INTO `coreshop_states` (`name`, `isoCode`, `active`, `countryId`) VALUES
('Baden-Württemberg',	'BW',	1,	1),
('Bayern',	'BY',	1,	1),
('Berlin',	'BE',	1,	1),
('Brandenburg',	'BR',	1,	1),
('Bremen',	'HB',	1,	1),
('Hamburg',	'HH',	1,	1),
('Hessen',	'HE',	1,	1),
('Mecklenburg-Vorpommern',	'MV',	1,	1),
('Niedersachsen',	'NI',	1,	1),
('Nordrhein-Westfalen',	'NW',	1,	1),
('Rheinland-Pfalz',	'RP',	1,	1),
('Saarland',	'SL',	1,	1),
('Sachsen',	'SN',	1,	1),
('Sachsen-Anhalt',	'ST',	1,	1),
('Schleswig-Holstein',	'SH',	1,	1),
('Thüringen',	'TH',	1,	1),
('Burgenland',	'BG',	1,	2),
('Carinthia',	'KA',	1,	2),
('Lower Austria',	'NO',	1,	2),
('Salzburg',	'SB',	1,	2),
('Styria',	'ST',	1,	2),
('Tyrol',	'TI',	1,	2),
('Upper Austria',	'OO',	1,	2),
('Vienna',	'WI',	1,	2),
('Vorarlberg',	'VB',	1,	2),
('Antwerp',	'AN',	1,	3),
('Brussels',	'BU',	1,	3),
('East Flanders',	'OV',	1,	3),
('Flemish Brabant',	'VB',	1,	3),
('Hainaut',	'HT',	1,	3),
('Liege',	'LG',	1,	3),
('Limburg',	'LI',	1,	3),
('Luxembourg',	'LX',	1,	3),
('Namur',	'NA',	1,	3),
('Walloon Brabant',	'BW',	1,	3),
('West Flanders',	'WV',	1,	3),
('Alberta',	'AB',	1,	4),
('British Columbia',	'BC',	1,	4),
('Manitoba',	'MB',	1,	4),
('New Brunswick',	'NB',	1,	4),
('Newfoundland and Labrador',	'NL',	1,	4),
('Northwest Territories',	'NT',	1,	4),
('Nova Scotia',	'NS',	1,	4),
('Nunavut',	'NU',	1,	4),
('Ontario',	'ON',	1,	4),
('Prince Edward Island',	'PE',	1,	4),
('Quebec',	'QC',	1,	4),
('Saskatchewan',	'SK',	1,	4),
('Yukon Territory',	'YT',	1,	4),
('Alabama',	'AL',	1,	21),
('Alaska',	'AK',	1,	21),
('Arizona',	'AZ',	1,	21),
('Arkansas',	'AR',	1,	21),
('California',	'CA',	1,	21),
('Colorado',	'CO',	1,	21),
('Connecticut',	'CT',	1,	21),
('Delaware',	'DE',	1,	21),
('Dist of Columbia',	'DC',	1,	21),
('Florida',	'FL',	1,	21),
('Georgia',	'GA',	1,	21),
('Hawaii',	'HI',	1,	21),
('Idaho',	'ID',	1,	21),
('Illinois',	'IL',	1,	21),
('Indiana',	'IN',	1,	21),
('Iowa',	'IA',	1,	21),
('Kansas',	'KS',	1,	21),
('Kentucky',	'KY',	1,	21),
('Louisiana',	'LA',	1,	21),
('Maine',	'ME',	1,	21),
('Maryland',	'MD',	1,	21),
('Massachusetts',	'MA',	1,	21),
('Michigan',	'MI',	1,	21),
('Minnesota',	'MN',	1,	21),
('Mississippi',	'MS',	1,	21),
('Missouri',	'MO',	1,	21),
('Montana',	'MT',	1,	21),
('Nebraska',	'NE',	1,	21),
('Nevada',	'NV',	1,	21),
('New Hampshire',	'NH',	1,	21),
('New Jersey',	'NJ',	1,	21),
('New Mexico',	'NM',	1,	21),
('New York',	'NY',	1,	21),
('North Carolina',	'NC',	1,	21),
('North Dakota',	'ND',	1,	21),
('Ohio',	'OH',	1,	21),
('Oklahoma',	'OK',	1,	21),
('Oregon',	'OR',	1,	21),
('Pennsylvania',	'PA',	1,	21),
('Rhode Island',	'RI',	1,	21),
('South Carolina',	'SC',	1,	21),
('South Dakota',	'SD',	1,	21),
('Tennessee',	'TN',	1,	21),
('Texas',	'TX',	1,	21),
('Utah',	'UT',	1,	21),
('Vermont',	'VT',	1,	21),
('Virginia',	'VA',	1,	21),
('Washington',	'WA',	1,	21),
('West Virginia',	'WV',	1,	21),
('Wisconsin',	'WI',	1,	21),
('Wyoming',	'WY',	1,	21);