services:
  CoreShop\Bundle\PimcoreBundle\AdminClass\EventListener\AdminJavascriptListener:
    arguments:
      - '%coreshop.all.pimcore.admin.js%'
      - '%coreshop.all.pimcore.admin.editmode_js%'
      - '%coreshop.all.pimcore.admin.css%'
      - '%coreshop.all.pimcore.admin.editmode_css%'
    tags:
      - { name: kernel.event_subscriber }

  CoreShop\Bundle\PimcoreBundle\AdminClass\EventListener\Grid\ObjectListFilterListener:
    arguments:
      - '@coreshop.registry.grid.filter'
    tags:
      - { name: kernel.event_listener, event: pimcore.admin.object.list.beforeListLoad, method: checkObjectList }
