services:
  CoreShop\Bundle\PimcoreBundle\EventListener\AdminJavascriptListener:
    arguments:
      - '%coreshop.all.pimcore.admin.js%'
      - '%coreshop.all.pimcore.admin.editmode_js%'
      - '%coreshop.all.pimcore.admin.css%'
      - '%coreshop.all.pimcore.admin.editmode_css%'
    tags:
      - { name: kernel.event_subscriber }
