coreshop_admin_messenger_count:
  path: /%coreshop.admin.route.base%/messenger/count
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listReceiverMessageCountAction
  options:
    expose: true

coreshop_admin_messenger_list_receivers:
  path: /%coreshop.admin.route.base%/messenger/list-receivers
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listListableReceiversAction
  options:
    expose: true

coreshop_admin_messenger_list_failed:
  path: /%coreshop.admin.route.base%/messenger/list-failed/{receiverName}
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listFailedMessagesAction
  options:
    expose: true

coreshop_admin_messenger_list:
  path: /%coreshop.admin.route.base%/messenger/list/{receiverName}
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listMessagesAction
  options:
    expose: true

coreshop_admin_messenger_list_failure_receivers:
  path: /%coreshop.admin.route.base%/messenger/list-failure-receivers
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listFailureReceiversAction
  options:
    expose: true

coreshop_admin_messenger_delete:
  path: /%coreshop.admin.route.base%/messenger/delete/{receiverName}
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\MessageController::deleteStoredMessageAction
  methods: 'DELETE'
  options:
    expose: true

coreshop_admin_messenger_retry:
  path: /%coreshop.admin.route.base%/messenger/retry/{receiverName}
  requirements:
    backend: '%coreshop.admin.route.backend_requirement%'
  defaults:
    backend: admin
    _controller: CoreShop\Bundle\MessengerBundle\Controller\MessageController::retryFailedMessageAction
  methods: 'POST'
  options:
    expose: true
