<?php

if (!defined("CORESHOP_PATH"))  define("CORESHOP_PATH", PIMCORE_PLUGINS_PATH. "/CoreShop");
if (!defined("CORESHOP_CONFIGURATION_PATH"))  define("CORESHOP_CONFIGURATION_PATH", PIMCORE_CONFIGURATION_DIRECTORY);
if (!defined("CORESHOP_CONFIGURATION"))  define("CORESHOP_CONFIGURATION", CORESHOP_CONFIGURATION_PATH . "/coreshop-config.xml");