services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Security\ShopUserAuthenticationSuccessHandler:
        arguments:
            - '@security.http_utils'

    CoreShop\Bundle\CoreBundle\Security\ShopUserAuthenticationFailureHandler:
        arguments:
            - '@http_kernel'
            - '@security.http_utils'

    CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler:
        arguments:
            - '@router'
            - '%coreshop.after_logout_redirect_route%'
            - '@CoreShop\Component\Store\Context\StoreContextInterface'
        tags:
            - name: 'kernel.event_listener'
              event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
              method: 'onLogoutSuccess'
              dispatcher: security.event_dispatcher.coreshop_frontend
