services:
    _defaults:
        public: true

    CoreShop\Bundle\CoreBundle\Menu\MainMenuBuilder:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: 'coreshop.menu', type: main, menu: main }
