<?php
/**
 * CoreShop
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.coreshop.org/license
 *
 * @copyright  Copyright (c) 2015 Dominik Pfaffenbauer (http://dominik.pfaffenbauer.at)
 * @license    http://www.coreshop.org/license     New BSD License
 */

namespace CoreShop\Helper;

class Country {

    protected static $countryMap = array(
        "AD" => "Andorra",
        "AE" => "United Arab Emirates",
        "AF" => "Afghanistan",
        "AG" => "Antigua and Barbuda",
        "AI" => "Anguilla",
        "AL" => "Albania",
        "AM" => "Armenia",
        "AN" => "Netherlands Antilles",
        "AO" => "Angola",
        "AQ" => "Antarctica",
        "AR" => "Argentina",
        "AS" => "American Samoa",
        "AT" => "Austria",
        "AU" => "Australia",
        "AW" => "Aruba",
        "AX" => "Åland Islands",
        "AZ" => "Azerbaijan",
        "BA" => "Bosnia and Herzegovina",
        "BB" => "Barbados",
        "BD" => "Bangladesh",
        "BE" => "Belgium",
        "BF" => "Burkina Faso",
        "BG" => "Bulgaria",
        "BH" => "Bahrain",
        "BI" => "Burundi",
        "BJ" => "Benin",
        "BL" => "Saint Barthélemy",
        "BM" => "Bermuda",
        "BN" => "Brunei Darussalam",
        "BO" => "Bolivia, Plurinational State of",
        "BQ" => "Bonaire, Sint Eustatius and Saba",
        "BR" => "Brazil",
        "BS" => "Bahamas",
        "BT" => "Bhutan",
        "BV" => "Bouvet Island",
        "BW" => "Botswana",
        "BY" => "Belarus",
        "BZ" => "Belize",
        "CA" => "Canada",
        "CC" => "Cocos (Keeling) Islands",
        "CD" => "Congo, the Democratic Republic of the",
        "CF" => "Central African Republic",
        "CG" => "Congo",
        "CH" => "Switzerland",
        "CI" => "Côte d'Ivoire",
        "CK" => "Cook Islands",
        "CL" => "Chile",
        "CM" => "Cameroon",
        "CN" => "China",
        "CO" => "Colombia",
        "CR" => "Costa Rica",
        "CS" => "Czechoslovak Socialist Republic",
        "CU" => "Cuba",
        "CV" => "Cape Verde",
        "CW" => "Curaçao",
        "CX" => "Christmas Island",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "DD" => "German Democratic Republic",
        "DE" => "Germany",
        "DJ" => "Djibouti",
        "DK" => "Denmark",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "DZ" => "Algeria",
        "EC" => "Ecuador",
        "EE" => "Estonia",
        "EG" => "Egypt",
        "EH" => "Western Sahara",
        "ER" => "Eritrea",
        "ES" => "Spain",
        "ET" => "Ethiopia",
        "FI" => "Finland",
        "FJ" => "Fiji",
        "FK" => "Falkland Islands (Malvinas)",
        "FM" => "Micronesia, Federated States of",
        "FO" => "Faroe Islands",
        "FR" => "France",
        "GA" => "Gabon",
        "GB" => "United Kingdom",
        "GD" => "Grenada",
        "GE" => "Georgia",
        "GF" => "French Guiana",
        "GG" => "Guernsey",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GL" => "Greenland",
        "GM" => "Gambia",
        "GN" => "Guinea",
        "GP" => "Guadeloupe",
        "GQ" => "Equatorial Guinea",
        "GR" => "Greece",
        "GS" => "South Georgia and the South Sandwich Islands",
        "GT" => "Guatemala",
        "GU" => "Guam",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HK" => "Hong Kong",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HR" => "Croatia",
        "HT" => "Haiti",
        "HU" => "Hungary",
        "ID" => "Indonesia",
        "IE" => "Ireland",
        "IL" => "Israel",
        "IM" => "Isle of Man",
        "IN" => "India",
        "IO" => "British Indian Ocean Territory",
        "IQ" => "Iraq",
        "IR" => "Iran, Islamic Republic of",
        "IS" => "Iceland",
        "IT" => "Italy",
        "JE" => "Jersey",
        "JM" => "Jamaica",
        "JO" => "Jordan",
        "JP" => "Japan",
        "KE" => "Kenya",
        "KG" => "Kyrgyzstan",
        "KH" => "Cambodia",
        "KI" => "Kiribati",
        "KM" => "Comoros",
        "KN" => "Saint Kitts and Nevis",
        "KP" => "Korea, Democratic People's Republic of",
        "KR" => "Korea, Republic of",
        "KW" => "Kuwait",
        "KY" => "Cayman Islands",
        "KZ" => "Kazakhstan",
        "LA" => "Lao People's Democratic Republic",
        "LB" => "Lebanon",
        "LC" => "Saint Lucia",
        "LI" => "Liechtenstein",
        "LK" => "Sri Lanka",
        "LR" => "Liberia",
        "LS" => "Lesotho",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "LV" => "Latvia",
        "LY" => "Libya",
        "MA" => "Morocco",
        "MC" => "Monaco",
        "MD" => "Moldova, Republic of",
        "ME" => "Montenegro",
        "MF" => "Saint Martin (French part)",
        "MG" => "Madagascar",
        "MH" => "Marshall Islands",
        "MK" => "Macedonia, The Former Yugoslav Republic of",
        "ML" => "Mali",
        "MM" => "Myanmar",
        "MN" => "Mongolia",
        "MO" => "Macao",
        "MP" => "Northern Mariana Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MS" => "Montserrat",
        "MT" => "Malta",
        "MU" => "Mauritius",
        "MV" => "Maldives",
        "MW" => "Malawi",
        "MX" => "Mexico",
        "MY" => "Malaysia",
        "MZ" => "Mozambique",
        "NA" => "Namibia",
        "NC" => "New Caledonia",
        "NE" => "Niger",
        "NF" => "Norfolk Island",
        "NG" => "Nigeria",
        "NI" => "Nicaragua",
        "NL" => "Netherlands",
        "NO" => "Norway",
        "NP" => "Nepal",
        "NR" => "Nauru",
        "NU" => "Niue",
        "NZ" => "New Zealand",
        "OM" => "Oman",
        "PA" => "Panama",
        "PE" => "Peru",
        "PF" => "French Polynesia",
        "PG" => "Papua New Guinea",
        "PH" => "Philippines",
        "PK" => "Pakistan",
        "PL" => "Poland",
        "PM" => "Saint Pierre and Miquelon",
        "PN" => "Pitcairn",
        "PR" => "Puerto Rico",
        "PS" => "Palestinian Territory, Occupied",
        "PT" => "Portugal",
        "PW" => "Palau",
        "PY" => "Paraguay",
        "QA" => "Qatar",
        "RE" => "Réunion",
        "RO" => "Romania",
        "RS" => "Serbia",
        "RU" => "Russian Federation",
        "RW" => "Rwanda",
        "SA" => "Saudi Arabia",
        "SB" => "Solomon Islands",
        "SC" => "Seychelles",
        "SD" => "Sudan",
        "SE" => "Sweden",
        "SG" => "Singapore",
        "SH" => "Saint Helena, Ascension and Tristan da Cunha",
        "SI" => "Slovenia",
        "SJ" => "Svalbard and Jan Mayen",
        "SK" => "Slovakia",
        "SL" => "Sierra Leone",
        "SM" => "San Marino",
        "SN" => "Senegal",
        "SO" => "Somalia",
        "SR" => "Suriname",
        "SS" => "South Sudan",
        "ST" => "Sao Tome and Principe",
        "SU" => "U.S.S.R.",
        "SV" => "El Salvador",
        "SX" => "Sint Maarten (Dutch part)",
        "SY" => "Syrian Arab Republic",
        "SZ" => "Swaziland",
        "TC" => "Turks and Caicos Islands",
        "TD" => "Chad",
        "TF" => "French Southern Territories",
        "TG" => "Togo",
        "TH" => "Thailand",
        "TJ" => "Tajikistan",
        "TK" => "Tokelau",
        "TL" => "Timor-Leste",
        "TM" => "Turkmenistan",
        "TN" => "Tunisia",
        "TO" => "Tonga",
        "TR" => "Turkey",
        "TT" => "Trinidad and Tobago",
        "TV" => "Tuvalu",
        "TW" => "Taiwan, Province of China",
        "TZ" => "Tanzania, United Republic of",
        "UA" => "Ukraine",
        "UG" => "Uganda",
        "UM" => "United States Minor Outlying Islands",
        "US" => "United States",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VA" => "Holy See (Vatican City State)",
        "VC" => "Saint Vincent and the Grenadines",
        "VE" => "Venezuela, Bolivarian Republic of",
        "VG" => "Virgin Islands, British",
        "VI" => "Virgin Islands, U.S.",
        "VN" => "Viet Nam",
        "VU" => "Vanuatu",
        "WF" => "Wallis and Futuna",
        "WS" => "Samoa",
        "YD" => "People's Democratic Republic of Yemen",
        "YE" => "Yemen",
        "YT" => "Mayotte",
        "YU" => "Yugoslavia",
        "ZA" => "South Africa",
        "ZM" => "Zambia",
        "ZR" => "Zaire",
        "ZW" => "Zimbabwe"
    );

    // PHP ISO country => currency list

    protected static $countryCurrencyMap = array(
        "AF" => "AFN",
        "AL" => "ALL",
        "DZ" => "DZD",
        "AS" => "USD",
        "AD" => "EUR",
        "AO" => "AOA",
        "AI" => "XCD",
        "AG" => "XCD",
        "AR" => "ARP",
        "AM" => "AMD",
        "AW" => "AWG",
        "AU" => "AUD",
        "AT" => "EUR",
        "AZ" => "AZN",
        "BS" => "BSD",
        "BH" => "BHD",
        "BD" => "BDT",
        "BB" => "BBD",
        "BY" => "BYR",
        "BE" => "EUR",
        "BZ" => "BZD",
        "BJ" => "XOF",
        "BM" => "BMD",
        "BT" => "BTN",
        "BO" => "BOV",
        "BA" => "BAM",
        "BW" => "BWP",
        "BV" => "NOK",
        "BR" => "BRL",
        "IO" => "USD",
        "BN" => "BND",
        "BG" => "BGL",
        "BF" => "XOF",
        "BI" => "BIF",
        "KH" => "KHR",
        "CM" => "XAF",
        "CA" => "CAD",
        "CV" => "CVE",
        "KY" => "KYD",
        "CF" => "XAF",
        "TD" => "XAF",
        "CL" => "CLF",
        "CN" => "CNY",
        "CX" => "AUD",
        "CC" => "AUD",
        "CO" => "COU",
        "KM" => "KMF",
        "CG" => "XAF",
        "CD" => "CDF",
        "CK" => "NZD",
        "CR" => "CRC",
        "HR" => "HRK",
        "CU" => "CUP",
        "CY" => "EUR",
        "CZ" => "CZK",
        "CS" => "CSJ",
        "CI" => "XOF",
        "DK" => "DKK",
        "DJ" => "DJF",
        "DM" => "XCD",
        "DO" => "DOP",
        "EC" => "USD",
        "EG" => "EGP",
        "SV" => "USD",
        "GQ" => "EQE",
        "ER" => "ERN",
        "EE" => "EEK",
        "ET" => "ETB",
        "FK" => "FKP",
        "FO" => "DKK",
        "FJ" => "FJD",
        "FI" => "FIM",
        "FR" => "XFO",
        "GF" => "EUR",
        "PF" => "XPF",
        "TF" => "EUR",
        "GA" => "XAF",
        "GM" => "GMD",
        "GE" => "GEL",
        "DD" => "DDM",
        "DE" => "EUR",
        "GH" => "GHC",
        "GI" => "GIP",
        "GR" => "GRD",
        "GL" => "DKK",
        "GD" => "XCD",
        "GP" => "EUR",
        "GU" => "USD",
        "GT" => "GTQ",
        "GN" => "GNE",
        "GW" => "GWP",
        "GY" => "GYD",
        "HT" => "USD",
        "HM" => "AUD",
        "VA" => "EUR",
        "HN" => "HNL",
        "HK" => "HKD",
        "HU" => "HUF",
        "IS" => "ISJ",
        "IN" => "INR",
        "ID" => "IDR",
        "IR" => "IRR",
        "IQ" => "IQD",
        "IE" => "IEP",
        "IL" => "ILS",
        "IT" => "ITL",
        "JM" => "JMD",
        "JP" => "JPY",
        "JO" => "JOD",
        "KZ" => "KZT",
        "KE" => "KES",
        "KI" => "AUD",
        "KP" => "KPW",
        "KR" => "KRW",
        "KW" => "KWD",
        "KG" => "KGS",
        "LA" => "LAJ",
        "LV" => "LVL",
        "LB" => "LBP",
        "LS" => "ZAR",
        "LR" => "LRD",
        "LY" => "LYD",
        "LI" => "CHF",
        "LT" => "LTL",
        "LU" => "LUF",
        "MO" => "MOP",
        "MK" => "MKN",
        "MG" => "MGF",
        "MW" => "MWK",
        "MY" => "MYR",
        "MV" => "MVR",
        "ML" => "MAF",
        "MT" => "MTL",
        "MH" => "USD",
        "MQ" => "EUR",
        "MR" => "MRO",
        "MU" => "MUR",
        "YT" => "EUR",
        "MX" => "MXV",
        "FM" => "USD",
        "MD" => "MDL",
        "MC" => "MCF",
        "MN" => "MNT",
        "ME" => "EUR",
        "MS" => "XCD",
        "MA" => "MAD",
        "MZ" => "MZM",
        "MM" => "MMK",
        "NA" => "ZAR",
        "NR" => "AUD",
        "NP" => "NPR",
        "NL" => "NLG",
        "AN" => "ANG",
        "NC" => "XPF",
        "NZ" => "NZD",
        "NI" => "NIO",
        "NE" => "XOF",
        "NG" => "NGN",
        "NU" => "NZD",
        "NF" => "AUD",
        "MP" => "USD",
        "NO" => "NOK",
        "OM" => "OMR",
        "PK" => "PKR",
        "PW" => "USD",
        "PA" => "USD",
        "PG" => "PGK",
        "PY" => "PYG",
        "YD" => "YDD",
        "PE" => "PEH",
        "PH" => "PHP",
        "PN" => "NZD",
        "PL" => "PLN",
        "PT" => "TPE",
        "PR" => "USD",
        "QA" => "QAR",
        "RO" => "ROK",
        "RU" => "RUB",
        "RW" => "RWF",
        "RE" => "EUR",
        "SH" => "SHP",
        "KN" => "XCD",
        "LC" => "XCD",
        "PM" => "EUR",
        "VC" => "XCD",
        "WS" => "WST",
        "SM" => "EUR",
        "ST" => "STD",
        "SA" => "SAR",
        "SN" => "XOF",
        "RS" => "CSD",
        "SC" => "SCR",
        "SL" => "SLL",
        "SG" => "SGD",
        "SK" => "SKK",
        "SI" => "SIT",
        "SB" => "SBD",
        "SO" => "SOS",
        "ZA" => "ZAL",
        "ES" => "ESB",
        "LK" => "LKR",
        "SD" => "SDG",
        "SR" => "SRG",
        "SJ" => "NOK",
        "SZ" => "SZL",
        "SE" => "SEK",
        "CH" => "CHW",
        "SY" => "SYP",
        "TW" => "TWD",
        "TJ" => "TJR",
        "TZ" => "TZS",
        "TH" => "THB",
        "TL" => "USD",
        "TG" => "XOF",
        "TK" => "NZD",
        "TO" => "TOP",
        "TT" => "TTD",
        "TN" => "TND",
        "TR" => "TRL",
        "TM" => "TMM",
        "TC" => "USD",
        "TV" => "AUD",
        "SU" => "SUR",
        "UG" => "UGS",
        "UA" => "UAK",
        "AE" => "AED",
        "GB" => "GBP",
        "US" => "USS",
        "UM" => "USD",
        "UY" => "UYI",
        "UZ" => "UZS",
        "VU" => "VUV",
        "VE" => "VEB",
        "VN" => "VNC",
        "VG" => "USD",
        "VI" => "USD",
        "WF" => "XPF",
        "EH" => "MAD",
        "YE" => "YER",
        "YU" => "YUM",
        "ZR" => "ZRZ",
        "ZM" => "ZMK",
        "ZW" => "ZWC"
    );

    protected static $currencyDetailMap = array(
        'AFA' => array('name' => 'Afghan Afghani', 'isocode' => '971', 'symbol' => 'Lek'),
        'AWG' => array('name' => 'Aruban Florin', 'isocode' => '533', 'symbol' => 'ƒ'),
        'AUD' => array('name' => 'Australian Dollars', 'isocode' => '036', 'symbol' => '$'),
        'ARS' => array('name' => 'Argentine Pes', 'isocode' => '032', 'symbol' => '$'),
        'AZN' => array('name' => 'Azerbaijanian Manat', 'isocode' => '944', 'symbol' => 'ман'),
        'BSD' => array('name' => 'Bahamian Dollar', 'isocode' => '044', 'symbol' => '$'),
        'BDT' => array('name' => 'Bangladeshi Taka', 'isocode' => '050', 'symbol' => '৳'),
        'BBD' => array('name' => 'Barbados Dollar', 'isocode' => '052', 'symbol' => '$'),
        'BYR' => array('name' => 'Belarussian Rouble', 'isocode' => '974', 'symbol' => 'p.'),
        'BOB' => array('name' => 'Bolivian Boliviano', 'isocode' => '068', 'symbol' => '$b'),
        'BRL' => array('name' => 'Brazilian Real', 'isocode' => '986', 'symbol' => 'R$'),
        'GBP' => array('name' => 'British Pounds Sterling', 'isocode' => '826', 'symbol' => '£'),
        'BGN' => array('name' => 'Bulgarian Lev', 'isocode' => '975', 'symbol' => 'лв'),
        'KHR' => array('name' => 'Cambodia Riel', 'isocode' => '116', 'symbol' => '៛'),
        'CAD' => array('name' => 'Canadian Dollars', 'isocode' => '124', 'symbol' => '$'),
        'KYD' => array('name' => 'Cayman Islands Dollar', 'isocode' => '136', 'symbol' => '$'),
        'CLP' => array('name' => 'Chilean Peso', 'isocode' => '152', 'symbol' => '$'),
        'CNY' => array('name' => 'Chinese Renminbi Yuan', 'isocode' => '156', 'symbol' => '¥'),
        'COP' => array('name' => 'Colombian Peso', 'isocode' => '170', 'symbol' => '$'),
        'CRC' => array('name' => 'Costa Rican Colon', 'isocode' => '188', 'symbol' => '₡'),
        'HRK' => array('name' => 'Croatia Kuna', 'isocode' => '191', 'symbol' => 'kn'),
        // 'CPY' => array('name' => 'Cypriot Pounds', 'isocode' => '196', 'symbol' => ''), //Historic
        'CZK' => array('name' => 'Czech Koruna', 'isocode' => '203', 'symbol' => 'Kč'),
        'DKK' => array('name' => 'Danish Krone', 'isocode' => '208', 'symbol' => 'kr'),
        'DOP' => array('name' => 'Dominican Republic Peso', 'isocode' => '214', 'symbol' => 'RD$'),
        'XCD' => array('name' => 'East Caribbean Dollar', 'isocode' => '951', 'symbol' => '$'),
        'EGP' => array('name' => 'Egyptian Pound', 'isocode' => '818', 'symbol' => '£'),
        'ERN' => array('name' => 'Eritrean Nakfa', 'isocode' => '232', 'symbol' => 'Nfa'),
        'EEK' => array('name' => 'Estonia Kroon', 'isocode' => '233', 'symbol' => 'kr'),
        'EUR' => array('name' => 'Euro', 'isocode' => '978', 'symbol' => '€'),
        'GEL' => array('name' => 'Georgian Lari', 'isocode' => '981', 'symbol' => 'GEL'), //Todo: SYMBOL
        'GHC' => array('name' => 'Ghana Cedi', 'isocode' => '288', 'symbol' => '¢'),
        'GIP' => array('name' => 'Gibraltar Pound', 'isocode' => '292', 'symbol' => '£'),
        'GTQ' => array('name' => 'Guatemala Quetzal', 'isocode' => '320', 'symbol' => 'Q'),
        'HNL' => array('name' => 'Honduras Lempira', 'isocode' => '340', 'symbol' => 'L'),
        'HKD' => array('name' => 'Hong Kong Dollars', 'isocode' => '344', 'symbol' => '$'),
        'HUF' => array('name' => 'Hungary Forint', 'isocode' => '348', 'symbol' => 'Ft'),
        'ISK' => array('name' => 'Icelandic Krona', 'isocode' => '352', 'symbol' => 'kr'),
        'INR' => array('name' => 'Indian Rupee', 'isocode' => '356', 'symbol' => '₹'),
        'IDR' => array('name' => 'Indonesia Rupiah', 'isocode' => '360', 'symbol' => 'Rp'),
        'ILS' => array('name' => 'Israel Shekel', 'isocode' => '376', 'symbol' => '₪'),
        'JMD' => array('name' => 'Jamaican Dollar', 'isocode' => '388', 'symbol' => 'J$'),
        'JPY' => array('name' => 'Japanese yen', 'isocode' => '392', 'symbol' => '¥'),
        'KZT' => array('name' => 'Kazakhstan Tenge', 'isocode' => '368', 'symbol' => 'лв'),
        'KES' => array('name' => 'Kenyan Shilling', 'isocode' => '404', 'symbol' => 'KSh'),
        'KWD' => array('name' => 'Kuwaiti Dinar', 'isocode' => '414', 'symbol' => 'د.ك'),
        'LVL' => array('name' => 'Latvia Lat', 'isocode' => '428', 'symbol' => 'Ls'),
        'LBP' => array('name' => 'Lebanese Pound', 'isocode' => '422', 'symbol' => '£'),
        'LTL' => array('name' => 'Lithuania Litas', 'isocode' => '440', 'symbol' => 'Lt'),
        'MOP' => array('name' => 'Macau Pataca', 'isocode' => '446', 'symbol' => 'MOP$'),
        'MKD' => array('name' => 'Macedonian Denar', 'isocode' => '807', 'symbol' => 'ден'),
        'MGA' => array('name' => 'Malagascy Ariary', 'isocode' => '969', 'symbol' => 'MGA'), //TODO: SYMBOL
        'MYR' => array('name' => 'Malaysian Ringgit', 'isocode' => '458', 'symbol' => 'RM'),
        // 'MTL' => array('name' => 'Maltese Lira', 'isocode' => '470', 'symbol' => ''), //Historic
        'BAM' => array('name' => 'Marka', 'isocode' => '977', 'symbol' => 'KM'),
        'MUR' => array('name' => 'Mauritius Rupee', 'isocode' => '480', 'symbol' => '₨'),
        'MXN' => array('name' => 'Mexican Pesos', 'isocode' => '484', 'symbol' => '$'),
        // 'MZM' => array('name' => 'Mozambique Metical', 'isocode' => '508', 'symbol' => ''), //Historic
        'NPR' => array('name' => 'Nepalese Rupee', 'isocode' => '524', 'symbol' => '₨'),
        'ANG' => array('name' => 'Netherlands Antilles Guilder', 'isocode' => '532', 'symbol' => 'ƒ'),
        'TWD' => array('name' => 'New Taiwanese Dollars', 'isocode' => '901', 'symbol' => 'NT$'),
        'NZD' => array('name' => 'New Zealand Dollars', 'isocode' => '554', 'symbol' => '$'),
        'NIO' => array('name' => 'Nicaragua Cordoba', 'isocode' => '558', 'symbol' => 'C$'),
        'NGN' => array('name' => 'Nigeria Naira', 'isocode' => '566', 'symbol' => '₦'),
        'KPW' => array('name' => 'North Korean Won', 'isocode' => '408', 'symbol' => '₩'),
        'NOK' => array('name' => 'Norwegian Krone', 'isocode' => '578', 'symbol' => 'kr'),
        'OMR' => array('name' => 'Omani Riyal', 'isocode' => '512', 'symbol' => '﷼'),
        'PKR' => array('name' => 'Pakistani Rupee', 'isocode' => '586', 'symbol' => '₨'),
        'PYG' => array('name' => 'Paraguay Guarani', 'isocode' => '600', 'symbol' => 'Gs'),
        'PEN' => array('name' => 'Peru New Sol', 'isocode' => '604', 'symbol' => 'S/.'),
        'PHP' => array('name' => 'Philippine Pesos', 'isocode' => '608', 'symbol' => '₱'),
        'QAR' => array('name' => 'Qatari Riyal', 'isocode' => '634', 'symbol' => '﷼'),
        'RON' => array('name' => 'Romanian New Leu', 'isocode' => '946', 'symbol' => 'lei'),
        'RUB' => array('name' => 'Russian Federation Ruble', 'isocode' => '643', 'symbol' => 'руб'),
        'SAR' => array('name' => 'Saudi Riyal', 'isocode' => '682', 'symbol' => '﷼'),
        // 'CSD' => array('name' => 'Serbian Dinar', 'isocode' => '891', 'symbol' => ''), //Historic
        'SCR' => array('name' => 'Seychelles Rupee', 'isocode' => '690', 'symbol' => '₨'),
        'SGD' => array('name' => 'Singapore Dollars', 'isocode' => '702', 'symbol' => '$'),
        // 'SKK' => array('name' => 'Slovak Koruna', 'isocode' => '703', 'symbol' => ''), //Historic
        // 'SIT' => array('name' => 'Slovenia Tolar', 'isocode' => '705', 'symbol' => ''), //Historic
        'ZAR' => array('name' => 'South African Rand', 'isocode' => '710', 'symbol' => 'R'),
        'KRW' => array('name' => 'South Korean Won', 'isocode' => '410', 'symbol' => '₩'),
        'LKR' => array('name' => 'Sri Lankan Rupee', 'isocode' => '144', 'symbol' => '₨'),
        'SRD' => array('name' => 'Surinam Dollar', 'isocode' => '968', 'symbol' => '$'),
        'SEK' => array('name' => 'Swedish Krona', 'isocode' => '752', 'symbol' => 'kr'),
        'CHF' => array('name' => 'Swiss Francs', 'isocode' => '756', 'symbol' => 'CHF'),
        'TZS' => array('name' => 'Tanzanian Shilling', 'isocode' => '834', 'symbol' => 'x/y'),
        'THB' => array('name' => 'Thai Baht', 'isocode' => '764', 'symbol' => '฿'),
        'TTD' => array('name' => 'Trinidad and Tobago Dollar', 'isocode' => '780', 'symbol' => 'TT$'),
        'TRY' => array('name' => 'Turkish New Lira', 'isocode' => '949', 'symbol' => '₺'),
        'AED' => array('name' => 'UAE Dirham', 'isocode' => '784', 'symbol' => 'د.إ'),
        'USD' => array('name' => 'US Dollars', 'isocode' => '840', 'symbol' => '$'),
        'UGX' => array('name' => 'Ugandian Shilling', 'isocode' => '800', 'symbol' => 'USh'),
        'UAH' => array('name' => 'Ukraine Hryvna', 'isocode' => '980', 'symbol' => '₴'),
        'UYU' => array('name' => 'Uruguayan Peso', 'isocode' => '858', 'symbol' => '$U'),
        'UZS' => array('name' => 'Uzbekistani Som', 'isocode' => '860', 'symbol' => 'лв'),
        // 'VEB' => array('name' => 'Venezuela Bolivar', 'isocode' => '862', 'symbol' => ''), //Historic
        'VND' => array('name' => 'Vietnam Dong', 'isocode' => '704', 'symbol' => '₫'),
        'AMK' => array('name' => 'Zambian Kwacha', 'isocode' => '894', 'symbol' => 'ZK'),
        'ZWD' => array('name' => 'Zimbabwe Dollar', 'isocode' => '716', 'symbol' => 'Z$'),
        'USS' => array('name' => 'United States dollar ', 'isocode' => '998', 'symbol' => '$')
    );

    public static function getCountries()
    {
        return self::$countryMap;
    }

    public static function getCurrencyCodeForCountry($countryCode)
    {
        if(array_key_exists($countryCode, self::$countryCurrencyMap))
            return self::$countryCurrencyMap[$countryCode];

        return false;
    }

    public static function getCurrencyDetail($currencyCode) {
        if(!is_string($currencyCode) && !is_int($currencyCode))
            return false;

        if(array_key_exists($currencyCode, self::$currencyDetailMap))
            return self::$currencyDetailMap[$currencyCode];

        return false;
    }
}