[program:pimcore_maintenance]
command=php /var/www/html/bin/console messenger:consume pimcore_maintenance --memory-limit=200M --time-limit=300
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:pimcore_images]
command=php /var/www/html/bin/console messenger:consume pimcore_asset_update pimcore_image_optimize --memory-limit=200M --time-limit=300
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:pimcore_core]
command=php /var/www/html/bin/console messenger:consume pimcore_core pimcore_scheduled_tasks scheduler_generic_data_index --memory-limit=200M --time-limit=300
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:pimcore_generic_data_index]
command=php /var/www/html/bin/console messenger:consume pimcore_generic_data_index_queue --memory-limit=250M --time-limit=3600
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:pimcore_generic_execution_engine]
command=php /var/www/html/bin/console messenger:consume pimcore_generic_execution_engine --memory-limit=250M --time-limit=3600
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:pimcore_maintenance_cron]
command=sh -c 'sleep 300 && exec php /var/www/html/bin/console pimcore:maintenance'
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:coreshop]
command=php /var/www/html/bin/console messenger:consume coreshop_notification coreshop_index coreshop_variant --memory-limit=250M --time-limit=3600
numprocs=1
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
