#!/usr/bin/env bash
set -e

mysql --version
mysql -e "SET GLOBAL innodb_file_format=Barracuda;"
mysql -e "SET GLOBAL innodb_large_prefix=1;"
mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

# Move CoreShop in Order to install Pimcore
mkdir $TRAVIS_BUILD_DIR/../lib
mkdir $TRAVIS_BUILD_DIR/../lib/CoreShop
mv $TRAVIS_BUILD_DIR/{.[!.],}* $TRAVIS_BUILD_DIR/../lib/CoreShop
rm -rf $TRAVIS_BUILD_DIR/{.[!.],}*

git clone https://github.com/pimcore/pimcore.git $TRAVIS_BUILD_DIR
git checkout ${PIMCORE_BRANCH} $TRAVIS_BUILD_DIR

# Move CoreShop into lib/CoreShop
mkdir $TRAVIS_BUILD_DIR/lib
mv $TRAVIS_BUILD_DIR/../lib/CoreShop $TRAVIS_BUILD_DIR/lib/CoreShop

cp $TRAVIS_BUILD_DIR/lib/CoreShop/etc $TRAVIS_BUILD_DIR/etc
chmod -R +x lib/CoreShop/etc/travis

phpenv config-add $TRAVIS_BUILD_DIR/../lib/CoreShop/.gitlab-ci/php.ini