coreshop_customer_password_reset_request:
    path:       /password-reset-request
    controller: CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetRequestAction

coreshop_customer_password_reset:
    path:       /password-reset
    controller: CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetAction

coreshop_login_check:
    path:       /login-check
    controller: CoreShop\Bundle\FrontendBundle\Controller\SecurityController::checkAction

coreshop_login:
    path:       /login
    controller: CoreShop\Bundle\FrontendBundle\Controller\SecurityController::loginAction

coreshop_logout:
    path:       /logout
    controller: CoreShop\Bundle\FrontendBundle\Controller\SecurityController::logoutAction

coreshop_register:
    path:       /register
    controller: CoreShop\Bundle\FrontendBundle\Controller\RegisterController::registerAction

coreshop_customer_change_password:
    path:       /customer/change-password
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::changePasswordAction

coreshop_customer_confirm_newsletter:
    path:       /customer/confirm-newsletter
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::confirmNewsletterAction

coreshop_customer_address_new:
    path:       /customer/address/new
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressAction

coreshop_customer_address_delete:
    path:       /customer/addresses/delete/{address}
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressDeleteAction
    requirements: { address: '\d+' }

coreshop_customer_address_edit:
    path:       /customer/address/{name}~a{address}
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressAction
    requirements: { name: '[^/]+', address: '\d+' }

coreshop_customer_addresses:
    path:       /customer/addresses
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressesAction

coreshop_customer_profile:
    path:       /customer/profile
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::profileAction

coreshop_customer_orders:
    path:       /customer/orders
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::ordersAction

coreshop_customer_order_detail:
    path:       /customer/order/{order}
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::orderDetailAction
    requirements: { order: '\d+' }

coreshop_customer_settings:
    path:       /customer/settings
    controller: CoreShop\Bundle\FrontendBundle\Controller\CustomerController::settingsAction
