coreshop_admin_variant_attributes:
    path: /%coreshop.admin.route.base%/variant/attributes
    requirements:
        backend: '%coreshop.admin.route.backend_requirement%'
    defaults:
        backend: admin
        _controller: CoreShop\Bundle\VariantBundle\Controller\VariantController::getAttributesAction
    options:
        expose: true

coreshop_admin_variant_generator:
    path: /%coreshop.admin.route.base%/variant/generate
    requirements:
        backend: '%coreshop.admin.route.backend_requirement%'
    defaults:
        backend: admin
        _controller: CoreShop\Bundle\VariantBundle\Controller\VariantController::generateVariantsAction
    methods: [POST]
    options:
        expose: true